### ISSUE TITLE
Cannot install system-wide due to unable to create some log file

### ISSUE THREAD

**Issue by stevenxxiu** [dan-oak/zsh-jupyter-kernel#21]
I'm trying out this package to write some documents with *Zsh* code in them.

I installed this to *JupyterHub* system-wide, however I'm unable to run any commands. I'm getting the error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/zsh_jupyter_kernel/__main__.py", line 2, in <module>
    from .kernel import ZshKernel
  File "/usr/lib/python3.9/site-packages/zsh_jupyter_kernel/kernel.py", line 10, in <module>
    from .config import config
  File "/usr/lib/python3.9/site-packages/zsh_jupyter_kernel/config.py", line 87, in <module>
    makedirs(dirname(config['logfile']), exist_ok = True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/lib/python3.9/site-packages/zsh_jupyter_kernel/log'
```

I don't see any logs in the source code anyway. Could this be removed? Thanks.

**Comment by dan-oak** [comment]
stopped creating log files in [3.4.1](https://pypi.org/project/zsh-jupyter-kernel/3.4.1/)
